version: "3.8"
services:
  app:
    build:
      args:
        user: testsphp
        uid: 1000
      context: ./
      dockerfile: ./.docker/app/Dockerfile
    image: testsphp
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker/php/backend.ini:/usr/local/etc/php/conf.d/backend.ini
    networks:
      - testsphp

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - testsphp

  postgres:
    image: postgres:13
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    networks:
      - testsphp

networks:
  testsphp:
    driver: bridge

volumes:
  postgres_data:
